Jozwiaczek/smart-gate

package.json
packages/client/src/containers/SignIn/index.tsx
packages/core/.eslintrc
packages/core/README.md
packages/core/package.json
packages/core/src/index.ts
packages/core/src/models.ts
packages/core/tsconfig.json

Add package core

---

README.md
_templates/admin-model/help/index.ejs.t
_templates/admin-model/new/inject_model.ejs.t
_templates/admin-model/new/inject_model_app_config.ejs.t
_templates/admin-model/new/inject_model_app_config_imports.ejs.t
_templates/admin-model/new/inject_model_app_config_resources.ejs.t
_templates/admin-model/new/model_create.ejs.t
_templates/admin-model/new/model_edit.ejs.t
_templates/admin-model/new/model_index.ejs.t
_templates/admin-model/new/model_list.ejs.t
_templates/admin-model/new/model_show.ejs.t
_templates/admin-model/new/model_show_basics_tabs.ejs.t
_templates/admin-model/new/model_show_tabs_index.ejs.t
_templates/admin-model/new/prompt.js
_templates/generator/help/index.ejs.t
_templates/generator/new/hello.ejs.t
_templates/generator/with-prompt/hello.ejs.t
_templates/generator/with-prompt/prompt.ejs.t
package.json
packages/admin/package.json
packages/admin/src/App.tsx
packages/admin/src/models/index.ts
packages/admin/src/models/users/Edit.tsx
packages/admin/src/models/users/index.ts
packages/admin/src/models/users/show/Show.tsx
packages/admin/src/models/users/show/tabs/BasicsTab.tsx
packages/admin/src/models/users/show/tabs/index.ts
packages/admin/tsconfig.json
yarn.lock

Add hygen generator

---

packages/api/.env.example
packages/api/docker-compose.yml
packages/api/docker/on-init-db.sh

feat(api): add postgres-multi-db script

---

packages/api/src/database/config/database-config.service.ts
packages/api/src/users/user.service.spec.ts
packages/api/src/users/users.service.spec.ts
packages/api/src/utils/cookiesUtils.ts
packages/api/test/globalSetup.ts
packages/api/test/utils/clearTestDatabase.ts
packages/api/test/utils/testCreateRandomUser.ts

- base test setup
- test for service user findOne and findOneByEmail
- replace ENV with NODE_ENV

feat(api): setup db for tests

---

packages/api/src/utils/cookiesUtils.ts

fix: cookie sameSite set to 'lax'

fix: cookie hot fix

---

packages/api/src/auth/auth.controller.ts
packages/api/src/auth/guards/only-authenticated.guard.ts
packages/api/src/utils/cookiesUtils.ts

fix: add cookie sign option and change sameSite

fix: Cookie-signature hot fix 

---

.github/workflows/continous_integration.yml
ci/setupTestDatabase.ts
package.json
packages/api/jest.config.js
packages/api/package.json
packages/api/src/database/config/database-config.service.ts
packages/api/test/globalSetup.ts
packages/api/test/utils/clearTestDatabase.ts
yarn.lock

Add CI step with tests

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/dependabot.yml
.github/workflows/continous_integration.yml
.huskyrc.js

Remove test check from pre-push git hooks and add linters in ci

---

packages/api/src/modules/database/migrations/1614634822580-init.ts

(hotFix) Generate new inti migration

---

README.md

Update README.md (#86)

---

packages/client/src/elements/Card/index.ts
packages/client/src/elements/Link/Link.styled.ts
packages/client/src/elements/Snackbar/Snackbar.styled.ts
packages/client/src/elements/animations/AnimatedLogo/AnimatedLogo.styled.ts
packages/client/src/elements/animations/AnimatedLogo/AnimatedLogo.types.d.ts
packages/client/src/elements/animations/AnimatedLogo/index.tsx
packages/client/src/elements/buttons/Button/Button.styled.ts
packages/client/src/elements/buttons/IconButton/index.ts
packages/client/src/elements/inputs/Checkbox/Checkbox.styled.ts
packages/client/src/elements/inputs/Checkbox/index.tsx
packages/client/src/elements/inputs/TextField/TextField.styled.ts
packages/client/src/theme/Theme.ts

feat(client): handle accessibility, handle animation logo on click

---

packages/client/src/containers/Dashboard/index.tsx
packages/client/src/containers/Login/index.tsx
packages/client/src/containers/Registration/index.tsx
packages/client/src/elements/Form/index.tsx
packages/client/src/elements/inputs/TextField/index.tsx
packages/client/src/i18n/resources/en.ts
packages/client/src/i18n/resources/pl.ts
packages/client/src/utils/index.ts
packages/client/src/utils/onlyOnDevEnv.ts

Add translations

---

packages/api/src/modules/auth/auth.controller.ts
packages/api/src/modules/auth/auth.service.ts
packages/api/src/modules/refresh-token/refresh-token.service.ts
packages/client/src/containers/Dashboard/index.tsx
packages/client/src/i18n/resources/en.ts
packages/client/src/i18n/resources/pl.ts
packages/client/src/providers/api/AuthProvider/AuthProvider.context.ts
packages/client/src/providers/api/AuthProvider/AuthProvider.types.d.ts
packages/client/src/providers/api/AuthProvider/index.tsx

Add logout from all devices

---

.github/workflows/release.yml

ci: check release pipeline

---

.github/workflows/release.yml
release.config.js

check release pipeline 933b99d

---

packages/api/.env.example
packages/api/src/main.ts
packages/api/src/modules/app.module.ts
packages/api/src/modules/config/config-loader.ts
packages/api/src/modules/config/config.module.ts
packages/api/src/modules/config/config.ts
packages/api/src/modules/config/environment-config/environment-config.module.ts
packages/api/src/modules/config/environment-config/environment-config.service.ts
packages/api/src/modules/database/config/database-config.module.ts
packages/api/src/modules/database/config/database-config.service.ts
packages/api/src/modules/mailer/config/mailer-config.module.ts
packages/api/src/modules/mailer/config/mailer-config.service.ts
packages/api/src/modules/mailer/mailer.module.ts
packages/api/src/modules/mailer/mailer.service.ts
packages/api/tsconfig.json
packages/client/src/hooks/useOnClickOutside.ts

feat(api): add global config module

---

.github/workflows/chromatic.yml
.github/workflows/codeql-analysis.yml
.github/workflows/continous_integration.yml
packages/client/README.md

ci: add chromatic pipeline

---

packages/client/package.json
packages/client/src/containers/Dashboard/index.tsx
packages/client/src/elements/AppBar/AppBar.stories.tsx
packages/client/src/elements/AppBar/AppBar.styled.ts
packages/client/src/elements/AppBar/AppBar.types.d.ts
packages/client/src/elements/AppBar/index.tsx
packages/client/src/providers/api/AuthProvider/AuthProvider.context.ts
packages/client/src/providers/api/AuthProvider/AuthProvider.types.d.ts
packages/client/src/providers/api/AuthProvider/index.tsx
packages/client/src/providers/api/ReactQueryProvider/ReactQueryProvider.d.ts
packages/client/src/providers/api/ReactQueryProvider/index.tsx
packages/client/src/providers/api/index.ts
packages/client/src/providers/index.tsx
packages/client/src/utils/testingLibraryInstance.tsx
yarn.lock

- setup react-query provider
- add react-query dev tools
- add example in dashboard
- remove unneeded console logs

feat: add react-query

---

.prettierignore
README.md
packages/client/README.md
packages/client/netlify.toml

docs: link to changelog in root readme

---

package.json
packages/api/package.json
packages/client/package.json
release.config.js

Release 29.03.2020 #2

---

packages/api/src/modules/database/config/database-config.service.ts

Set database ssl on

---

release.config.js

Release 29.03.2021 v2

---

package.json
packages/api/package.json
packages/api/src/modules/config/config-loader.ts
packages/api/src/modules/config/config.ts
packages/api/src/modules/config/defaultValues.ts
packages/api/src/modules/mailer/config/mailer-config.service.ts
packages/client/package.json

Add mail 'from' header

---

packages/api/src/onInit.ts

Hot fix: error message on sentry disable

---

packages/client/package.json
packages/client/src/elements/AppBar/index.tsx
packages/client/src/elements/buttons/IconButton/IconButton.styled.ts
packages/client/src/elements/buttons/IconButton/IconButton.types.d.ts
packages/client/src/elements/buttons/IconButton/index.tsx
packages/client/src/elements/layouts/TabbedLayout/Tab/Tab.styled.ts
packages/client/src/elements/layouts/TabbedLayout/Tab/Tab.types.d.ts
packages/client/src/elements/layouts/TabbedLayout/Tab/index.tsx
packages/client/src/elements/layouts/TabbedLayout/TabbedLayout.stories.tsx
packages/client/src/elements/layouts/TabbedLayout/Tabs/Tabs.styled.ts
packages/client/src/elements/layouts/TabbedLayout/Tabs/Tabs.types.d.ts
packages/client/src/elements/layouts/TabbedLayout/Tabs/Tabs.utils.ts
packages/client/src/elements/layouts/TabbedLayout/Tabs/index.tsx

Scrollable tabbed layout

---

.github/workflows/release.yml
packages/client/package.json
packages/client/src/elements/AppBar/index.tsx
packages/client/src/elements/buttons/IconButton/IconButton.styled.ts
packages/client/src/elements/buttons/IconButton/IconButton.types.d.ts
packages/client/src/elements/buttons/IconButton/index.tsx
packages/client/src/elements/layouts/TabbedLayout/Tab/Tab.styled.ts
packages/client/src/elements/layouts/TabbedLayout/Tab/Tab.types.d.ts
packages/client/src/elements/layouts/TabbedLayout/Tab/index.tsx
packages/client/src/elements/layouts/TabbedLayout/TabbedLayout.stories.tsx
packages/client/src/elements/layouts/TabbedLayout/Tabs/Tabs.styled.ts
packages/client/src/elements/layouts/TabbedLayout/Tabs/Tabs.types.d.ts
packages/client/src/elements/layouts/TabbedLayout/Tabs/Tabs.utils.ts
packages/client/src/elements/layouts/TabbedLayout/Tabs/index.tsx
yarn.lock

Release 11.04.21

---

packages/client/src/elements/AppBar/AppBar.styled.ts
packages/client/src/elements/inputs/Select/Select.styled.ts
packages/client/src/elements/inputs/Select/Select.types.d.ts
packages/client/src/elements/inputs/Select/index.tsx
packages/client/src/elements/lists/DetailedList/DetailedList.styled.ts
packages/client/src/elements/lists/DetailedList/DetailedList.types.d.ts
packages/client/src/elements/lists/DetailedList/Pagination/Pagination.styled.ts
packages/client/src/elements/lists/DetailedList/Pagination/Pagination.types.d.ts
packages/client/src/elements/lists/DetailedList/Pagination/index.tsx
packages/client/src/elements/lists/DetailedList/index.tsx
packages/client/src/pages/authorized/admin/AdminDashboard/AdminDashboard.styled.ts
packages/client/src/pages/authorized/admin/Users/Users.styled.ts

Full height list

---

.github/workflows/release.yml

Release #2 - 11.04.21

---

.github/workflows/release.yml

Release #3 - 11.04.21

---

.github/workflows/pr-auto-approve.yml
.github/workflows/release.yml
release.config.js

Release #4 - 11.04.21

---

packages/client/src/elements/AppBar/AppBar.styled.ts

fix(client): add additional bottom padding for mobile app bar

---

packages/client/src/elements/AppBar/index.tsx

BUG FIX: mobile tabbed view routing

---

packages/api/src/modules/auth/cookie/config/cookie-config.service.ts

FIX: Set cookie samesite to 'strict'

---

packages/api/src/main.ts
packages/client/public/_redirects
packages/client/src/providers/api/AxiosProvider/index.tsx

Add client api proxy

---

packages/api/src/main.ts

Add api cors

---

packages/api/src/main.ts
yarn.lock

Release 16.04.2021 v2

---

.run/hygen_client_icon.run.xml
packages/client/_templates/icon/help/index.ejs.t
packages/client/_templates/icon/new/icon.ejs.t
packages/client/_templates/icon/new/inject_icon_index.ejs.t
packages/client/_templates/icon/new/inject_icon_story.ejs.t
packages/client/_templates/icon/new/inject_icon_story_import.ejs.t
packages/client/_templates/icon/new/prompt.js
packages/client/package.json

feat(client): add icon component generator

---

packages/client/src/elements/fields/Fields.types.d.ts
packages/client/src/elements/lists/DetailedList/index.tsx
packages/client/src/pages/authorized/admin/Invitations/index.tsx

Fix(client)/handle list fields no translation option

---

packages/client/src/providers/api/AxiosProvider/index.tsx

fix(client): handle axios base url for development environment

---

packages/api/src/modules/database/entities/invitation.entity.ts
packages/api/src/modules/database/migrations/1621545394649-InvitationCreatedByNullable.ts
packages/api/src/modules/invitations/dto/invitation-item.dto.ts
packages/api/src/modules/invitations/dto/removeMany-invitation.dto.ts
packages/api/src/modules/invitations/invitations.controller.ts
packages/api/src/modules/invitations/invitations.service.spec.ts
packages/api/src/modules/invitations/invitations.service.ts
packages/client/src/elements/fields/DateField/index.tsx
packages/client/src/i18n/resources/en.ts
packages/client/src/i18n/resources/pl.ts
packages/client/src/pages/authorized/Admin/Invitations/SendInvitationButtonWithDialog.tsx
packages/client/src/pages/authorized/Admin/Invitations/index.tsx
packages/client/src/providers/api/ReactQueryProvider/index.tsx

[Fix] Invitation list

---

packages/e2e/plugins/email-account.ts

fix(e2e): criteria for searching emails

---

.github/workflows/chromatic.yml

ci: change chromatic workflow run condition

---

.github/pull_request_template.md
README.md
packages/client/netlify.toml

docs: add links to missing packages, add root scripts

---

package.json
packages/client/package.json
packages/client/src/elements/Form/Form.types.d.ts
packages/client/src/elements/Form/index.tsx
packages/client/src/elements/inputs/TextInput/TextInput.types.d.ts
packages/client/src/pages/unauthorized/PasswordRecovery/UpdatePassword/index.tsx
packages/client/src/pages/unauthorized/Registration/index.tsx
yarn.lock

chore: bump-deps and fix form types

---

.all-contributorsrc
.github/pull_request_template.md
.github/workflows/chromatic.yml
README.md
package.json
packages/client/netlify.toml
packages/client/package.json
packages/client/src/elements/Form/Form.types.d.ts
packages/client/src/elements/Form/index.tsx
packages/client/src/elements/inputs/TextInput/TextInput.types.d.ts
packages/client/src/pages/unauthorized/PasswordRecovery/UpdatePassword/index.tsx
packages/client/src/pages/unauthorized/Registration/index.tsx
packages/e2e/plugins/email-account.ts
yarn.lock

Release - 6/14/21

---

.github/workflows/continous_integration.yml
packages/api/package.json
packages/client/src/hooks/useOnClickOutside.ts

fix(api): types for prod env

---

.github/workflows/continous_integration.yml
packages/api/package.json
packages/client/src/hooks/useOnClickOutside.ts

Release - 6/27/21

---

packages/api/src/modules/config/config-loader.ts

fix(api): loading port env

---

.github/pull_request_template.md
.github/workflows/continous_integration.yml
packages/ci-scripts/package.json
packages/ci-scripts/src/createEmailTestAccount.ts

ci: handle e2e secrets in ci

---

packages/client/src/elements/animations/Checkmark/Checkmark.stories.tsx
packages/client/src/elements/animations/Checkmark/Checkmark.types.d.ts
packages/client/src/elements/animations/Checkmark/index.tsx
packages/client/src/elements/animations/ThemeTypeIndicator/ThemeTypeIndicator.stories.tsx
packages/client/src/icons/TickIcon.tsx

Fix(client)/tick icon on iOS devices

---

packages/client/src/pages/authorized/Dashboard/sections/TogglingSection/index.tsx
packages/client/src/providers/api/WebSocketProvider/index.tsx

fix(client): handle socket connect and disconnect in provider layer

---

README.md
packages/client/netlify.toml

Release - 8/28/21

---

packages/api/src/modules/camera/camera.controller.ts
packages/api/src/modules/camera/camera.module.ts
packages/client/src/pages/authorized/Dashboard/sections/CameraPreviewSection/index.tsx

fix: change camera auth layer for ticket service

---

packages/api/src/modules/camera/camera.controller.ts
packages/api/src/modules/camera/camera.module.ts
packages/client/src/pages/authorized/Dashboard/sections/CameraPreviewSection/index.tsx

Release - 9/21/21
